// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: operation.proto

#include "operation.pb.h"
#include "operation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace operation {

static const char* Operation_method_names[] = {
  "/operation.Operation/SayHello",
};

std::unique_ptr< Operation::Stub> Operation::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Operation::Stub> stub(new Operation::Stub(channel));
  return stub;
}

Operation::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(Operation_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Operation::Stub::SayHello(::grpc::ClientContext* context, const ::operation::OperationRequest& request, ::operation::OperationReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Operation::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::operation::OperationRequest* request, ::operation::OperationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Operation::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::operation::OperationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Operation::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::operation::OperationRequest* request, ::operation::OperationReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

void Operation::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::operation::OperationReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::operation::OperationReply>* Operation::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::operation::OperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::operation::OperationReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::operation::OperationReply>* Operation::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::operation::OperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::operation::OperationReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

Operation::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Operation_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Operation::Service, ::operation::OperationRequest, ::operation::OperationReply>(
          std::mem_fn(&Operation::Service::SayHello), this)));
}

Operation::Service::~Service() {
}

::grpc::Status Operation::Service::SayHello(::grpc::ServerContext* context, const ::operation::OperationRequest* request, ::operation::OperationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace operation

